### ISSUE TITLE
Add me to Team section

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens.domains#16]
Brantly Millegan
Developer Relations
![brantly millegan headshot](https://user-images.githubusercontent.com/30162762/59151030-43398200-89e1-11e9-90be-64eb2c8bbb19.JPG)

**Comment by jefflau** [comment]
@rliebert90 Can you make this black and white like the others?

**Comment by rliebert90** [comment]
@jefflau here's the png of the asset for Brantly's team photo: 
![Brantly_ENS](https://user-images.githubusercontent.com/45074845/59641881-fcf6c800-9130-11e9-914b-9ef35f4f10d0.png)

**Comment by brantlymillegan** [comment]
@jefflau can we get this added?

**Comment by jefflau** [comment]
@brantlymillegan I’ll get this done when I’m back to work next week

**Comment by brantlymillegan** [comment]
@jefflau Thanks, but my picture and name links to Beltran's Twitter account right now. Here is my Twitter account: https://twitter.com/brantlymillegan
