### ISSUE TITLE
Indicator to scroll down

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens.domains#18]
There is no indicator that one should scroll down, and clicking on Ethereum Name Service in the middle doesn't do anything (Firefox). This leads to a confusing first user experience.

@rliebert90

**Comment by rliebert90** [comment]
@jefflau how about we add this subtle indicator that could stick to the bottom of a user's browser and fade out once you start scrolling? It'd look like this: 
<img width="1435" alt="Screen Shot 2019-07-25 at 12 08 28 PM" src="https://user-images.githubusercontent.com/45074845/61890814-4972b780-aed6-11e9-88bd-ac67b306a3b2.png">

If you're good with this, here's the sketch file! https://www.dropbox.com/s/bzjpdifxhkg3equ/ens.domains_scroll.sketch?dl=0

**Comment by brantlymillegan** [comment]
Closed since we're revamping the whole design of the homepage
