### ISSUE TITLE
Set Address record, transaction confirmed, but it's still not showing up on record page

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens.domains#24]
Just as the title said, see the record for brantly.xyz
![Screen Shot 2019-08-27 at 9 55 53 AM](https://user-images.githubusercontent.com/30162762/63793243-2449de00-c8b4-11e9-8929-a080839097ed.png)

**Comment by woodydeck** [comment]
I'm also having trouble with the indexing. I released a bunch of domains, but they are still showing up next to my address. There's no ability to manually reindex an address' portfolio of domains.

@brantlymillegan As for your problem, I've had it take between 2 and 5 minutes to display correctly. I am not sure which node they are using for this, but could have something to do with lag in that.

**Comment by jefflau** [comment]
Moving this to ens-app repo
