### ISSUE TITLE
Setting a resolver is confusing

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens.domains#25]
When you try to set a resolver, it shows you a field that says "Enter Ethereum name or address." This is confusing because people could think they're supposed to put their own Ethereum address there. Also, 99.999% of people are going to use the Public Resolver, so it shouldn't be a small link under the field.

I would at least change the text to say something more like "Enter contract address of custom resolver or use Public Resolver".

And really, it should just default to the Public Resolver anyway, with setting a custom resolver being an "Advanced Option" or something.

**Comment by syscoinethereum** [comment]
So after I do the new migration.

What should go in my resolver?

Where do I input my ether addy to be the owner?
