### ISSUE TITLE
Torque.loans at Apps Supporting ENS

### ISSUE THREAD

**Issue by sneg55** [ensdomains/ens.domains#26]
can we add Torque.loans at Apps Supporting ENS section?

Torque using first-of-its-kind ENS loan system which allows users to borrow assets by simply sending collateral to a human-readable ENS domain from any wallet.

More info: https://medium.com/bzxnetwork/introducing-torque-borrowing-made-simple-8eb494925d16  

url: https://torque.loans 
logo: 
![torque-logo-90px-w](https://user-images.githubusercontent.com/7769371/65902256-d458ae00-e36e-11e9-9858-4d79c35e4567.png)

**Comment by sneg55** [comment]
@makoto @Arachnid

**Comment by jefflau** [comment]
Added

**Comment by sneg55** [comment]
![image](https://user-images.githubusercontent.com/7769371/66052476-81553700-e4e5-11e9-97fc-59828fc7dd72.png)

Missing 

> https://

thus causing 404 

![image](https://user-images.githubusercontent.com/7769371/66052538-992cbb00-e4e5-11e9-9685-d7e0e7d79d18.png)
