### ISSUE TITLE
app.ens.domains occasionally unstable in Brave

### ISSUE THREAD

**Issue by cleanappio** [ensdomains/ens.domains#36]
no idea what the issue may be but the app occasionally crashes in Brave (v 0.66.100). 

Happened just a few times: 

(1) very first time loading, got stuck in a recursive flicker (seemed to load, but display unstable);
(2) second time don't recall exact sequence, but same symptom (flicker) 
(2) once after using the app with no problem in Brave, it just bounced back into the strobe-like flicker.

No such problems in Chrome, where it works flawlessly. Just wanted to mention -- fwiw.  Each time fixed just by closing & reloading tab. 

Thx for this great tool -- btw!

-- just updated to 0.70.123 & will let you know if it comes back.

**Comment by brantlymillegan** [comment]
Can you check to see if you are still having this problem? Thanks
