### ISSUE TITLE
Add prominent ENS App CTA on the landing page

### ISSUE THREAD

**Issue by shazow** [ensdomains/ens.domains#38]
Hi there, maybe it's just me but I couldn't find the link to https://app.ens.domains/ for several minutes. ~As far as I can tell, it's not linked anywhere on the landing page, https://ens.domains/ -- should it be?~ Edit: Just re-read the landing page a ~4th time and noticed the "Getting Started" links which I didn't realize were links, they looked like feature badges. IMO the most prominent CTA right now is "Join Now" in the footer. Also 2/4 of them go to the same URL now, maybe worth making it a more prominent button?

My process:
- I wanted to check if an ENS domain was available
- Googled "ens domains"
- Landed on ens.domains
- Read the whole page 2-3 times, couldn't find a link to the registry app (I couldn't remember the URL, tried registry.ens.domains from memory but that was wrong)
- Googled "register ens domain", still no link to the app, lots of blog posts that mostly link to ens.domains
- Had to dig up an old email with a direct link to find app.ens.domains

**Comment by makoto** [comment]
@Arachnid @brantlymillegan Becca,  I think this makes sense. Let me know if you want me to make a change or not.

**Comment by brantlymillegan** [comment]
This will get fixed in our homepage revamp we're working on, so I will close this
