### ISSUE TITLE
Some homepage typo fixes

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens.domains#46]
"burner" should be "Burner" (capitalized) and should link to https://wallet.burnerfactory.com/ (rather than just back to the ENS homepage)

"Enjinx" should be "EnjinX" (with the X capitalized)

"Encirca" should be "EnCirca" (with the C capitalized)

"D'Cent Wallet" should be "D'CENT Wallet" (all of the first word capitalized)

"Pandax" should be "PandaX" (X capitalized)

The link in the footer to our forum should say "Forum" (linked to https://discuss.ens.domains/)

For the section "Get Started using ENS"
1) The buttons "Register a .eth domain" and "Manage your domains" should both be links directly to "app.ens.domains"

2) The wording on the buttons should be changed to:
"Register a .ETH name"
"Manage your names"

3) In the section heading, "Using" should be capitalized

**Comment by brantlymillegan** [comment]
"Enjinx" should be "EnjinX" (with the X capitalized)

"Encirca" should be "EnCirca" (with the C capitalized)

**Comment by brantlymillegan** [comment]
For the section "Get Started using ENS"

1) The buttons "Register a .eth domain" and "Manage your domains" should both be links directly to "app.ens.domains"

2) The wording on the buttons should be changed to:
"Register a .ETH name"
"Manage your names"

3) In the section heading, "Using" should be capitalized

**Comment by brantlymillegan** [comment]
The link in the footer to our forum should say "Forum" (linked to https://discuss.ens.domains/)

**Comment by makoto** [comment]
https://github.com/ensdomains/ens.domains/pull/54
