### ISSUE TITLE
Permissions to create a PR to update defizap logo

### ISSUE THREAD

**Issue by Tosh-Sharma** [ensdomains/ens.domains#49]
Hi team, 

I have cloned your code and made changes on a separate branch to update the DeFiZap logo and URL text. Could you please provide access to raise a PR for this repository.

If this is not the right way to go about it, please let me know the best way to do this.

Regards,
Tosh Sharma

**Comment by brantlymillegan** [comment]
@makoto @jefflau

**Comment by makoto** [comment]
Hi, @Tosh-Sharma . Please fork our repo first.
I added the link to our readme https://github.com/ensdomains/ens.domains#0-prep-work-fork-our-repo

**Comment by makoto** [comment]
Handled at https://github.com/ensdomains/ens.domains/pull/53
