### ISSUE TITLE
Add new person to Team section

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens.domains#71]
Jim McDonald
http://linkedin.com/in/jimgmcdonald
EthDNS developer
![Headshot 2015 square](https://user-images.githubusercontent.com/30162762/73090052-6e97b100-3e8c-11ea-9b6f-bfbcae677a54.png)

**Comment by makoto** [comment]
Please ask @rliebert90 to modify the photo to be in the same color and shape as the rest of us first.

**Comment by rliebert90** [comment]
![Jim_McDonald](https://user-images.githubusercontent.com/45074845/73239359-e22a0e80-4169-11ea-9339-ff98c40fe275.png)

@brantlymillegan and @makoto here is the edited png!

**Comment by makoto** [comment]
Done https://github.com/ensdomains/ens.domains/pull/73
