### ISSUE TITLE
Combine "Mobile Wallets" and "Desktop Wallets" section on homepage

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens.domains#86]
Many wallets have both mobile and desktop version (or, if they're web-based, can be accessed on either). I would simply combine the two wallets sections into one. I would change the name of one of the MetaMask logos to "MetaMask Mobile" since they're mobile app is a significantly different product than their browser extension in my mind. Otherwise, all the logos can simply be combined into one category.

**Comment by makoto** [comment]
@brantlymillegan @rliebert90 don't we need a new icon representing wallet? The current icon is either a mobile phone or laptop

**Comment by rliebert90** [comment]
@makoto yes, we'd need a new icon if we combine those sections! Just emailed it to you.

**Comment by makoto** [comment]
https://github.com/ensdomains/ens.domains/pull/90
