### ISSUE TITLE
Add new company logos

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens.domains#9]
![opera](https://user-images.githubusercontent.com/1221141/55051096-c1e37c00-508e-11e9-9589-9b54b856687d.png) Opera for desktop wallets
![pandax](https://user-images.githubusercontent.com/1221141/55051099-c3ad3f80-508e-11e9-8b63-2e07aee8e2b8.jpg) Pandax for mobile wallets
![universal login](https://user-images.githubusercontent.com/1221141/55051101-c5770300-508e-11e9-9862-6f61d7b38cd7.png) Universal Login for apps

**Comment by brantlymillegan** [comment]
Portal Network (under apps)
https://resolver.portal.network/
![portal network](https://user-images.githubusercontent.com/30162762/55103963-bbe99d00-5086-11e9-8f30-c2703a55d48b.png)

**Comment by brantlymillegan** [comment]
Alpha Wallet
https://alphawallet.com/
![alphawallet logo](https://user-images.githubusercontent.com/30162762/55705718-c7dc4400-5a22-11e9-8ff9-87a7ca34171c.png)

**Comment by brantlymillegan** [comment]
Totem
https://totem.network/
![totem](https://user-images.githubusercontent.com/30162762/56089542-e9807400-5ed7-11e9-9362-61a9605203a3.png)

**Comment by brantlymillegan** [comment]
Please remove Mist (it's on the Desktop Wallet section)

**Comment by makoto** [comment]
Done.

<img width="532" alt="Screenshot 2019-04-16 at 14 24 53" src="https://user-images.githubusercontent.com/2630/56213190-7b60bc00-6053-11e9-85e6-5a246877fc70.png">
