### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens.domains#96]
Draft of new copy
https://docs.google.com/document/d/1D8CVLXL6HRfYGsWysANIZunoJY6P1EKi469EqFWBp_U/edit?usp=sharing

**Comment by brantlymillegan** [comment]
Copy on About page on app.ens.domains should also be revamped at the same time

**Comment by makoto** [comment]
@brantlymillegan Please provide some visual indication of which part of wording fits into which section of current page (commented in the draft google doc) .

**Comment by brantlymillegan** [comment]
I discussed this with Makoto on Keybase, but just to note it here: The copy is just in the order it needs to be on the page. Re exactly how that fits into the code of the page, I don't know. Makoto said he'd therefore leave this to @jefflau and @rliebert90 .

**Comment by rliebert90** [comment]
I’ve been working on the redesign of ens.domains (using your copy doc @brantlymillegan), and I have a couple versions I’m excited to share with the team. It’d be great to get all of your eyes on this, but finding an overlapping time may be a little difficult. @makoto your timing is the hardest to fit in with everyone else’s. If you had to sit this out, we could choose a later time for Jeff, and I can share the designs here for you to see after we review together. 

I’m wrapping up some details with these versions atm, but I’ll be ready to share the work early next week. How about during one of these windows of time on Monday, May 18 (Tuesday for Jeff and Nick)? 

* Me: 7pm - 10pm
* @jefflau 7am - 10am 
* @Arachnid 11am-2pm 
* @brantlymillegan  4pm-7pm 
* @makoto 12am-3am

**Comment by brantlymillegan** [comment]
@rliebert90 Good idea. Looking forward to seeing what you have! Anytime in that range works for me. I'm going to move this meeting time scheduling conversation to Keybase

**Comment by brantlymillegan** [comment]
@rliebert90 Looking forward to the meeting next week to go over this. Anything you can share in advance so we can have time to look it over?

**Comment by rliebert90** [comment]
@brantlymillegan I'd rather walk you guys through the work in our meeting tonight before sharing a preview. I’d like to give context for certain decisions with the layout and some suggested rephrasing of bits of copy. But right after our call, I’ll send a pdf of the designs so you guys can take some time to individually capture notes and send any feedback my way.

**Comment by rliebert90** [comment]
pdf of designs from last night's call (pre-revisions): 

https://www.dropbox.com/s/kjk2uietuc69ndj/ens.domains_redesign_05.18.2020.pdf?dl=0
